name: hali_saha_bak
description: A new Flutter project.

publish_to: 'none'

version: 3.8.10+13

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  animations: ^2.0.2
  cached_network_image: ^3.2.0
  share_plus: ^4.5.3
  cloud_firestore: ^3.1.10
  connectivity_plus: ^2.3.7
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  intl_phone_number_input: ^0.7.1
  firebase_messaging: ^11.2.13
  firebase_storage: ^10.2.9
  flashy_tab_bar2: ^0.0.4
  flutter:
    sdk: flutter
  flutter_credit_card: ^3.0.1
  flutter_inappwebview: any
  flutter_local_notifications: ^9.4.0
  flutter_rating_stars: ^1.0.3+4
  http: ^0.13.4
  iban: ^1.0.1
  image_picker: ^0.8.4+11
  intl: ^0.17.0
  intl_phone_field: ^3.0.1
  lottie: ^1.3.0
  modal_bottom_sheet: ^2.1.2
  new_version: ^0.3.1
  photo_view: ^0.13.0
  pinput: ^2.2.10
  provider: ^6.0.2
  quiver: ^3.1.0
  random_string: ^2.3.1
  selectable_container: ^1.0.2
  shared_preferences: ^2.0.13
  smooth_page_indicator: ^1.0.0+2
  time_range: ^1.0.2
  timezone: ^0.8.0
  twilio_flutter: ^0.0.9
  url_launcher: ^6.0.20
  webview_flutter: ^3.0.2
  webview_flutter_plus: ^0.3.0+2
  workmanager: ^0.5.0
  share: ^2.0.4

dependency_overrides:
  flutter_inappwebview:
    git:
      url: https://github.com/pichillilorenzo/flutter_inappwebview
      ref: master
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/location.png
    - assets/images/features/
    - assets/json/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
